INSERT INTO Product(PROD_Name, PROD_Price) VALUES("AA MEINL", 2150.00);
INSERT INTO Product(PROD_Name, PROD_Price) VALUES("Richo SP C220N", 4700.00);
INSERT INTO Product(PROD_Name, PROD_Price) VALUES("Casio G-shock", 3500.00);
INSERT INTO Product(PROD_Name, PROD_Price) VALUES("DJI SPARK COMBO", 21000.00);
INSERT INTO Product(PROD_Name, PROD_Price) VALUES("Michael Kors", 5690.00);